import { budgetMonthForDate } from "./budget";
import type { FinanceData, Transaction } from "./types";

const tx = (transaction: Omit<Transaction, "budget_month"> & { budget_month?: string }): Transaction => ({
  ...transaction,
  budget_month: transaction.budget_month ?? budgetMonthForDate(transaction.date),
  direction: transaction.direction ?? (transaction.type === "income" || transaction.type === "reimbursement" ? "in" : "out"),
  cleared_status: transaction.cleared_status ?? "cleared",
  linked_type: transaction.linked_type ?? "manual",
});

const demoCompanyExpenseItems: FinanceData["company_expense_items"] = [
  {
    id: "demo-ce-001",
    claim_month: "June Budget",
    date: "2026-06-04",
    site: "Customer A",
    project: "Network Project",
    place: "Site A",
    sale_name: "Sales A",
    sr: "SR-0001",
    detail: "Onsite support travel",
    expense_type: "Travel",
    amount: 900,
    status: "draft",
    note: "Demo data only",
  },
  {
    id: "demo-ce-002",
    claim_month: "June Budget",
    date: "2026-06-04",
    site: "Customer A",
    project: "Network Project",
    place: "Site A",
    sale_name: "Sales A",
    sr: "SR-0001",
    detail: "Onsite toll fee",
    expense_type: "Toll",
    amount: 120,
    status: "draft",
    note: "Demo data only",
  },
  {
    id: "demo-ce-003",
    claim_month: "June Budget",
    date: "2026-06-05",
    site: "Customer B",
    project: "Security Project",
    place: "Site B",
    sale_name: "Sales B",
    sr: "SR-0002",
    detail: "Training allowance",
    expense_type: "Training",
    amount: 400,
    status: "draft",
    note: "Demo data only",
  },
];

const demoCompanyOptions: FinanceData["company_options"] = [
  { kind: "site", name: "Customer A", active: true },
  { kind: "site", name: "Customer B", active: true },
  { kind: "project", name: "Network Project", active: true },
  { kind: "project", name: "Security Project", active: true },
  { kind: "place", name: "Site A", active: true },
  { kind: "place", name: "Site B", active: true },
  { kind: "sale", name: "Sales A", active: true },
  { kind: "sale", name: "Sales B", active: true },
];

export const sampleData: FinanceData = {
  wallet_snapshots: [
    { wallet: "KBANK", snapshot_date: "2026-06-13", balance: 5000 },
    { wallet: "BBL", snapshot_date: "2026-06-13", balance: 0 },
    { wallet: "MAKE", snapshot_date: "2026-06-13", balance: 1000 },
    { wallet: "TTB", snapshot_date: "2026-06-13", balance: 0 },
    { wallet: "CASH", snapshot_date: "2026-06-13", balance: 200 },
  ],
  transactions: [
    tx({
      id: "demo-salary",
      date: "2026-05-29",
      amount: 30000,
      type: "income",
      category: "salary",
      wallet: "TTB",
      payment_method: "promptpay",
      note: "Demo salary for June Budget",
      tags: "demo,salary",
    }),
    tx({
      id: "demo-grocery",
      date: "2026-06-14",
      amount: 159,
      type: "expense",
      category: "shopping",
      wallet: "KBANK",
      payment_method: "wallet",
      note: "Demo shopping transaction",
      tags: "demo",
    }),
  ],
  cards: [
    { card_name: "Main Card", statement_cycle: "monthly statement", due_day: 1, current_balance: 0 },
    { card_name: "Backup Card", statement_cycle: "monthly statement", due_day: 5, current_balance: 0 },
  ],
  card_items: [
    {
      id: "demo-card-001",
      date: "2026-06-14",
      card: "Main Card",
      amount: 300,
      merchant_note: "Demo toll top-up by credit card",
      category: "transport",
      claim_status: "review",
      paid_status: "unpaid",
      statement_month: "June Budget",
    },
  ],
  claims: [
    { claim_month: "June Budget", submit_by: "2026-07-05", expected_paid_date: "2026-07-10", status: "draft", paid_amount: 0 },
  ],
  claim_items: [
    {
      source_type: "card_item",
      source_id: "demo-card-001",
      amount: 300,
      work_personal_mixed: "review",
      status: "review",
      note: "Demo claim review item",
    },
  ],
  company_expense_items: demoCompanyExpenseItems,
  company_options: demoCompanyOptions,
  ot_claim_items: [
    {
      id: "demo-ot-001",
      claim_month: "May Budget",
      pay_month: "June Budget",
      date: "2026-05-31",
      start_time: "18:00",
      end_time: "21:00",
      ot_1x_hours: 0,
      ot_1_5x_hours: 3,
      ot_3x_hours: 0,
      site: "Customer A",
      project: "Network Project",
      detail: "Demo after-hours support",
      sale_name: "Sales A",
      billable: "",
      so: "",
      status: "submitted",
      base_rate: 189.5,
      expected_amount: 852.75,
      note: "Demo data only",
    },
  ],
  bills: [
    {
      id: "demo-bill-internet",
      name: "Internet bill",
      amount: 750,
      due_date: "2026-07-01",
      planned_pay_date: "2026-06-30",
      status: "unpaid",
      source: "Demo monthly bill",
    },
    {
      id: "demo-bill-card",
      name: "Main card statement",
      amount: 300,
      due_date: "2026-07-01",
      planned_pay_date: "2026-06-30",
      status: "unpaid",
      source: "Demo card statement",
    },
  ],
};
